### ISSUE TITLE
Ticking Entity: Mutant Enderman

### ISSUE THREAD

**Issue by IRonicBruh** [Chumbanotz/MutantBeasts#13]
---- Minecraft Crash Report ----
// There are four lights!

Time: 5/4/20 11:49 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at java.util.concurrent.ConcurrentLinkedDeque.<init>(ConcurrentLinkedDeque.java:849) ~[?:1.8.0_212] {}
	at svenhjol.strange.scrolls.event.QuestEvents.respondToEvent(QuestEvents.java:198) ~[?:1.15.2-1.0.0-beta.3] {re:classloading}
	at svenhjol.strange.scrolls.event.QuestEvents.onMobKilled(QuestEvents.java:178) ~[?:1.15.2-1.0.0-beta.3] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_371_QuestEvents_onMobKilled_LivingDeathEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:349) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:anviltweaks.mixins.json:ForgeHooksMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70645_a(LivingEntity.java:1077) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:charm:LivingEntity,xf:fml:caelus:coremodone,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at chumbanotz.mutantbeasts.entity.mutant.MutantEndermanEntity.func_70609_aI(MutantEndermanEntity.java:786) ~[?:1.15.2-1.0.5] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70030_z(LivingEntity.java:351) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:charm:LivingEntity,xf:fml:caelus:coremodone,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70030_z(MobEntity.java:207) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:368) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Entity Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2024) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:charm:LivingEntity,xf:fml:caelus:coremodone,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:536) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.concurrent.ConcurrentLinkedDeque.<init>(ConcurrentLinkedDeque.java:849)
	at svenhjol.strange.scrolls.event.QuestEvents.respondToEvent(QuestEvents.java:198)
	at svenhjol.strange.scrolls.event.QuestEvents.onMobKilled(QuestEvents.java:178)
	at net.minecraftforge.eventbus.ASMEventHandler_371_QuestEvents_onMobKilled_LivingDeathEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:349)
	at net.minecraft.entity.LivingEntity.func_70645_a(LivingEntity.java:1077)
	at chumbanotz.mutantbeasts.entity.mutant.MutantEndermanEntity.func_70609_aI(MutantEndermanEntity.java:786)
	at net.minecraft.entity.LivingEntity.func_70030_z(LivingEntity.java:351)
	at net.minecraft.entity.MobEntity.func_70030_z(MobEntity.java:207)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:368)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2024)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600)

-- Entity being ticked --
Details:
	Entity Type: mutantbeasts:mutant_enderman (chumbanotz.mutantbeasts.entity.mutant.MutantEndermanEntity)
	Entity ID: 72100
	Entity Name: Mutant Enderman
	Entity's Exact location: 52.93, 67.00, -308.34
	Entity's Block location: World: (52,67,-309), Chunk: (at 4,4,11 in 3,-20; contains blocks 48,0,-320 to 63,255,-305), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:536)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401)

-- Affected level --
Details:
	All players: 3 total; [ServerPlayerEntity['Super_Man_Hacker'/37136, l='world', x=-679.96, y=61.70, z=-843.84], ServerPlayerEntity['W0LFooo'/43750, l='world', x=38.08, y=64.00, z=-307.41], ServerPlayerEntity['twisted_miner1'/41547, l='world', x=41.50, y=66.00, z=-110.50]]
	Chunk stats: ServerChunkCache: 4708
	Level dimension: DimensionType{minecraft:overworld}
	Level name: world
	Level seed: -664295474497568865
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (-42,65,-298), Chunk: (at 6,4,6 in -3,-19; contains blocks -48,0,-304 to -33,255,-289), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 7485422 game time, 871192 day time
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 83787 (now: false), thunder time: 93692 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 4.4.0-151-generic
	Java Version: 1.8.0_212, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 536733912 bytes (511 MB) / 1636548608 bytes (1560 MB) up to 10468982784 bytes (9984 MB)
	CPUs: 4
	JVM Flags: 15 total; -Xms1G -Xmx10G -XX:+AggressiveOpts -XX:ParallelGCThreads=3 -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:NewSize=84m -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge.jar object_holder_definalize PLUGINSERVICE 
		/forge.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge.jar capability_inject_definalize PLUGINSERVICE 
		/forge.jar runtimedistcleaner PLUGINSERVICE 
		/forge.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.41
	FML Language Providers: 
		javafml@31.1
		minecraft@1
		kotlinfml@1.5.1
	Mod List: 
		inftrading_1.15.2-1.0.jar Infinite Trading {inftrading@1.0 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		glasscutter-1.0.1-1.15.2.jar Glasscutter {glasscutter@1.0.1 DONE}
		doubledoors_1.15-2.0.jar Double Doors {doubledoors@2.0 DONE}
		roughmobsrevamped-1.15.2-4.1.1.jar Rough Mobs Revamped {roughmobsrevamped@version DONE}
		CraftingAutomat-MC1.15.2-1.2.1.jar Crafting Automat {craftingautomat@1.2.1 DONE}
		PreGenForge-0.1.0-mc1.15.2.jar PreGenForge {pregenforge@0.1.0 DONE}
		DeathCounter-1.15.2-1.2.0.jar Death Counter {deathcounter@1.2.0 DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		metalbarrels-2.1.jar Metal Barrels {metalbarrels@2.1 DONE}
		goblintraders-1.2.0-1.15.2.jar Goblin Traders {goblintraders@1.2.0 DONE}
		caelus-FORGE-1.15.2-2.0-beta2.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta2 DONE}
		Upgrade-Aquatic-1.15.2-v1.5.1.jar Upgrade Aquatic {upgrade_aquatic@1.5.1 DONE}
		SilentMechanisms-1.15.2-0.7.0+50.jar Silent's Mechanisms {silents_mechanisms@0.7.0+50 DONE}
		BetterStorageToo-1.15.2-5.0.1.0.jar BetterStorageToo {betterstorage@1.15.2-5.0.1.0 DONE}
		essentials-1.15.2-2.7.0.jar Essentials {essentials@1.15.2-2.7.0 DONE}
		Waystones_1.15.2-6.0.1.jar Waystones {waystones@6.0.1 DONE}
		glassential-forge-1.15.2-1.1.2.jar Glassential {glassential@1.1.2 DONE}
		TerraForged-1.15.2-0.0.13.jar TerraForged {terraforged@0.0.13 DONE}
		journeymap-1.15.2-5.7.0b2.jar Journeymap {journeymap@5.7.0b2 DONE}
		CookingForBlockheads_1.15.2-8.0.1.jar Cooking for Blockheads {cookingforblockheads@8.0.1 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		decorative_blocks-6d.jar Decorative Blocks {decorative_blocks@1.6 DONE}
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 DONE}
		MutantBeasts-1.15.2-1.0.5.jar Mutant Beasts {mutantbeasts@1.15.2-1.0.5 DONE}
		FarmingForBlockheads_1.15.2-6.1.2.jar Farming for Blockheads {farmingforblockheads@6.1.2 DONE}
		Bookshelf-1.15.2-5.5.33.jar Bookshelf {bookshelf@5.5.33 DONE}
		Coins-1.15.2-1.0.1.jar Coins {coins@1.0.1 DONE}
		The-Endergetic-Expansion-1.15.2-v1.2.8.jar The Endergetic Expansion {endergetic@1.2.8 DONE}
		guardvillagers-1.15.2-1.0.6.jar Guard Villagers {guardvillagers@1.0.6 DONE}
		randompatches-1.15.2-1.21.1.2.jar RandomPatches {randompatches@1.15.2-1.21.1.2 DONE}
		ProgressiveBosses-2.1.5-mc1.15.2.jar Progressive Bosses {progressivebosses@2.1.5-mc1.15.2 DONE}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version DONE}
		mapperbase-1.15.2-1.1.0.0.jar Mapper Base {mapperbase@1.15.2-1.1.0.0 DONE}
		dragondropsel_1.15.2-1.0.jar Dragon Drops Elytra {dragondropsel@1.0 DONE}
		travellersboots-1.15.2-1.3.2.jar Traveller's Boots {travellersboots@1.3.1 DONE}
		forge-1.15.2-31.1.41-universal.jar Forge {forge@31.1.41 DONE}
		SimpleOres2-1.15.2-2.1.5.1.jar Simple Ores {simpleores@1.15.2-2.1.5.1 DONE}
		extendedfurnace-2.2.jar Extended Furnace {extendedfurnace@2.2 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		anviltweaks-2.3.jar Anvil Tweaks {anviltweaks@2.3 DONE}
		forge-1.15.2-31.1.41-server.jar Minecraft {minecraft@1.15.2 DONE}
		repurposedstructures-1.15.2-1.4.0.jar Repurposed Structures {repurposed_structures@1.15.2-1.4.0 DONE}
		theoneprobe-1.15-2.0.2.jar The One Probe {theoneprobe@1.15-2.0.2 DONE}
		embellishcraft-1.15.2-2.2.0.0.jar EmbellishCraft {embellishcraft@1.15.2-2.2.0.0 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		SilentLib-1.15.2-4.6.1+49.jar Silent Lib {silentlib@4.6.1+49 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		valhelsia_structures-15.0.2a.jar Valhelsia Structures {valhelsia_structures@15.0.2a DONE}
		concreteconversion-1.15.2-4.1.0.0.jar Concrete Conversion {concreteconversion@1.15.2-4.1.0.0 DONE}
		playerhopper-1.15-1.3.jar Player Hopper {playerhopper@1.15-1.3 DONE}
		simplefarming-1.15.2-1.2.7.jar Simple Farming {simplefarming@1.15.2-1.2.7 DONE}
		GeneticAnimals-0_5_3.jar Genetic Animals {eanimod@0_5_3 DONE}
		extragolems-10.1.1.jar Extra Golems {golems@10.1.1 DONE}
		dimdungeons-1.051-forge-1.15.2.jar Dimensional Dungeons {dimdungeons@1.15.2-1.05 DONE}
		curios-FORGE-1.15.2-2.0.2.2.jar Curios API {curios@FORGE-1.15.2-2.0.2.2 DONE}
		horse_colors-1.15.2-1.1.3.jar Realistic Horse Genetics {horse_colors@1.15.2-1.1.2 DONE}
		performant-1.15-2.09m.jar Performant {performant@2.09m DONE}
		backpacked-1.4.1-1.15.2.jar Backpacked {backpacked@1.4.1 DONE}
		harvest-1.15.2-1.0.1.jar Harvest {harvest@1.0.1 DONE}
		Gobber2-1.15.2-2.2.90.jar Gobber 2 {gobber2@2.2.90 DONE}
		grindr-1.15.2-0.0.1.5.jar Grindr {grindr@1.15.2-0.0.1.5 DONE}
		AttainedDrops-1.15.2-6.0.7.jar Attained Drops {attained_drops@6.0.7 DONE}
		PowderPower-1.15.2-3.1.61.jar Powder Power {powder_power@3.1.61 DONE}
		noRecipeBook_v1.5.4formc1.15.2.jar No Recipe Book {norecipebook@1.5.4 DONE}
		Project MMO-1.15-2.25.1.jar Project MMO {pmmo@2.25.1 DONE}
		curiouselytra-FORGE-1.15.2-2.0.jar Curious Elytra {curiouselytra@FORGE-1.15.2-2.0 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		moredragoneggs-1.0.jar More Dragon Eggs {moredragoneggs@1.0 DONE}
		Biomes_You_Go-0.3.3-BETA.jar Oh The Biomes You'll Go {byg@0.2.1 DONE}
		Charm-1.15.2-1.5.7.jar Charm {charm@1.15.2-1.5.7 DONE}
		Strange-1.15.2-1.0.0-beta.3.jar Strange {strange@1.15.2-1.0.0-beta.3 DONE}
		classicbar-3.0.2.jar Classic Bar {classicbar@3.0.2 DONE}
		EnderMail-1.15.2-1.1.0.jar Ender Mail {endermail@1.15.2-1.1.0 DONE}
		TrinityWeapons-1.15.2-1.4.1.jar TrinityWeapons {trinity@1.4.1 DONE}
		farlanders-1.15.2-1.1.2.jar The Farlanders {farlanders@1.1.2 DONE}
	Player Count: 3 / 20; [ServerPlayerEntity['Super_Man_Hacker'/37136, l='world', x=-679.96, y=61.70, z=-843.84], ServerPlayerEntity['W0LFooo'/43750, l='world', x=38.08, y=64.00, z=-307.41], ServerPlayerEntity['twisted_miner1'/41547, l='world', x=41.50, y=66.00, z=-110.50]]
	Data Packs: vanilla, mod:aiimprovements (incompatible), mod:anviltweaks (incompatible), mod:attained_drops (incompatible), mod:backpacked (incompatible), mod:betterstorage (incompatible), mod:bookshelf (incompatible), mod:byg, mod:caelus (incompatible), mod:charm (incompatible), mod:classicbar (incompatible), mod:coins (incompatible), mod:concreteconversion (incompatible), mod:craftingautomat (incompatible), mod:curios (incompatible), mod:curiouselytra (incompatible), mod:deathcounter (incompatible), mod:dimdungeons, mod:doubledoors (incompatible), mod:dragondropsel (incompatible), mod:dungeoncrawl (incompatible), mod:embellishcraft (incompatible), mod:endergetic (incompatible), mod:endermail (incompatible), mod:essentials (incompatible), mod:extendedfurnace (incompatible), mod:farlanders (incompatible), mod:forge (incompatible), mod:glasscutter, mod:gobber2 (incompatible), mod:goblintraders, mod:golems (incompatible), mod:grindr, mod:guardvillagers (incompatible), mod:harvest (incompatible), mod:horse_colors, mod:inftrading (incompatible), mod:inventorysorter (incompatible), mod:ironchest, mod:jei (incompatible), mod:journeymap (incompatible), mod:mapperbase, mod:metalbarrels (incompatible), mod:moredragoneggs, mod:morpheus (incompatible), mod:mousetweaks (incompatible), mod:mutantbeasts (incompatible), mod:norecipebook, mod:performant (incompatible), mod:placebo (incompatible), mod:playerhopper (incompatible), mod:pmmo (incompatible), mod:powder_power (incompatible), mod:pregenforge (incompatible), mod:progressivebosses, mod:randompatches (incompatible), mod:repurposed_structures, mod:roughmobsrevamped (incompatible), mod:silentlib (incompatible), mod:silents_mechanisms (incompatible), mod:simplefarming, mod:simpleores (incompatible), mod:strange (incompatible), mod:terraforged, mod:theoneprobe (incompatible), mod:travellersboots (incompatible), mod:trinity (incompatible), mod:upgrade_aquatic (incompatible), mod:valhelsia_structures (incompatible), mod:waystones (incompatible), file/fossil_dungeons.zip (incompatible), file/illager-fortresses-v6-for-1-15-2.zip (incompatible), mod:eanimod (incompatible), mod:cookingforblockheads (incompatible), mod:decorative_blocks, mod:farmingforblockheads (incompatible), mod:glassential (incompatible), mod:phosphor
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Chumbanotz** [comment]
Try the version just released and try to recreate what happened when the crash occurred. https://www.curseforge.com/minecraft/mc-mods/mutant-beasts/files
