### ISSUE TITLE
The 1.15.2 version crashes when installed on a dedicated server

### ISSUE THREAD

**Issue by rikka0w0** [Chumbanotz/MutantBeasts#17]
Forge version: forge-1.15.2-31.1.87

[m[1;31m[01:45:58] [Server thread/FATAL] [cp.mo.mo.TransformerClassWriter/]: Class net/minecraft/entity/IChargeableMob unable to find resource null
[m[1;31m[01:45:58] [Server thread/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: Failed to load hierarchy member net/minecraft/entity/IChargeableMob
Index: 2
Listeners:
0: NORMAL
1: ASM: class chumbanotz.mutantbeasts.RegistryHandler registerBlocks(Lnet/minecraftforge/event/RegistryEvent$Register;)V
2: ASM: class chumbanotz.mutantbeasts.RegistryHandler registerItems(Lnet/minecraftforge/event/RegistryEvent$Register;)V
3: ASM: class chumbanotz.mutantbeasts.RegistryHandler registerEntityTypes(Lnet/minecraftforge/event/RegistryEvent$Register;)V
4: ASM: class chumbanotz.mutantbeasts.RegistryHandler registerSoundEvents(Lnet/minecraftforge/event/RegistryEvent$Register;)V
5: ASM: class chumbanotz.mutantbeasts.RegistryHandler registerTileEntityTypes(Lnet/minecraftforge/event/RegistryEvent$Register;)V
6: ASM: class chumbanotz.mutantbeasts.RegistryHandler registerParticleTypes(Lnet/minecraftforge/event/RegistryEvent$Register;)V
java.lang.RuntimeException: Failed to load hierarchy member net/minecraft/entity/IChargeableMob
at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:86)
at cpw.mods.modlauncher.TransformerClassWriter.access$100(TransformerClassWriter.java:35)
at cpw.mods.modlauncher.TransformerClassWriter$SuperCollectingVisitor.lambda$visit$0(TransformerClassWriter.java:136)
at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
at cpw.mods.modlauncher.TransformerClassWriter$SuperCollectingVisitor.visit(TransformerClassWriter.java:135)
at org.objectweb.asm.ClassReader.accept(ClassReader.java:533)
at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:83)
at cpw.mods.modlauncher.TransformerClassWriter.access$100(TransformerClassWriter.java:35)
at cpw.mods.modlauncher.TransformerClassWriter$SuperCollectingVisitor.visit(TransformerClassWriter.java:129)
at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:340)
at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:74)
at cpw.mods.modlauncher.TransformerClassWriter.<init>(TransformerClassWriter.java:48)
at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:239)
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:126)
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96)
at java.lang.ClassLoader.loadClass(Unknown Source)
at chumbanotz.mutantbeasts.entity.MBEntityType.initialize(MBEntityType.java:93)
at chumbanotz.mutantbeasts.RegistryHandler.registerItems(RegistryHandler.java:43)
at net.minecraftforge.eventbus.ASMEventHandler_24_RegistryHandler_registerItems_Register.invoke(.dynamic)
at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
at java.util.function.Consumer.lambda$andThen$0(Unknown Source)
at java.util.function.Consumer.lambda$andThen$0(Unknown Source)
at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:126)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:126)
at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96)
at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71)
at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:214)
at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$25(ModLoader.java:206)
at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:971)
at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:206)
at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45)
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613)
at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Class not found
at org.objectweb.asm.ClassReader.readStream(ClassReader.java:310)
at org.objectweb.asm.ClassReader.<init>(ClassReader.java:283)
at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:82)
... 41 more

[m[1;31m[01:45:58] [Server thread/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Caught exception during event RegistryEvent.Register<minecraft:item> dispatch for modid mutantbeasts
java.lang.RuntimeException: Failed to load hierarchy member net/minecraft/entity/IChargeableMob
at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:86) ~[modlauncher-5.1.0.jar:?] {}
at cpw.mods.modlauncher.TransformerClassWriter.access$100(TransformerClassWriter.java:35) ~[modlauncher-5.1.0.jar:?] {}
at cpw.mods.modlauncher.TransformerClassWriter$SuperCollectingVisitor.lambda$visit$0(TransformerClassWriter.java:136) ~[modlauncher-5.1.0.jar:?] {}
at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_151] {}
at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:1.8.0_151] {}
at cpw.mods.modlauncher.TransformerClassWriter$SuperCollectingVisitor.visit(TransformerClassWriter.java:135) ~[modlauncher-5.1.0.jar:?] {}
at org.objectweb.asm.ClassReader.accept(ClassReader.java:533) ~[asm-7.2.jar:7.2] {}
at org.objectweb.asm.ClassReader.accept(ClassReader.java:400) ~[asm-7.2.jar:7.2] {}
at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:83) ~[modlauncher-5.1.0.jar:?] {}
at cpw.mods.modlauncher.TransformerClassWriter.access$100(TransformerClassWriter.java:35) ~[modlauncher-5.1.0.jar:?] {}
at cpw.mods.modlauncher.TransformerClassWriter$SuperCollectingVisitor.visit(TransformerClassWriter.java:129) ~[modlauncher-5.1.0.jar:?] {}
at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:340) ~[asm-tree-7.2.jar:7.2] {}
at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:74) ~[modlauncher-5.1.0.jar:?] {}
at cpw.mods.modlauncher.TransformerClassWriter.<init>(TransformerClassWriter.java:48) ~[modlauncher-5.1.0.jar:?] {}
at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-5.1.0.jar:?] {}
at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:239) ~[modlauncher-5.1.0.jar:?] {}
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:126) ~[modlauncher-5.1.0.jar:?] {}
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) ~[modlauncher-5.1.0.jar:?] {}
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151] {}
at chumbanotz.mutantbeasts.entity.MBEntityType.initialize(MBEntityType.java:93) ~[?:1.15.2-1.0.1] {re:classloading,pl:object_holder_definalize:A}
at chumbanotz.mutantbeasts.RegistryHandler.registerItems(RegistryHandler.java:43) ~[?:1.15.2-1.0.1] {re:classloading}
at net.minecraftforge.eventbus.ASMEventHandler_24_RegistryHandler_registerItems_Register.invoke(.dynamic) ~[?:?] {}
at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) ~[?:31.1] {re:classloading}
at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_151] {}
at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_151] {}
at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?] {re:classloading}
at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:126) ~[?:?] {re:classloading}
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_151] {}
at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:1.8.0_151] {}
at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:126) ~[?:?] {re:classloading}
at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96) ~[?:?] {re:classloading}
at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71) ~[?:?] {re:classloading}
at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:214) ~[?:?] {re:classloading}
at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$25(ModLoader.java:206) ~[?:?] {re:classloading}
at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:971) [?:?] {re:classloading}
at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:206) [?:?] {re:classloading}
at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) [?:?] {re:classloading}
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) [?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at java.lang.Thread.run(Unknown Source) [?:1.8.0_151] {}
Caused by: java.io.IOException: Class not found
at org.objectweb.asm.ClassReader.readStream(ClassReader.java:310) ~[asm-7.2.jar:7.2] {}
at org.objectweb.asm.ClassReader.<init>(ClassReader.java:283) ~[asm-7.2.jar:7.2] {}
at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:82) ~[modlauncher-5.1.0.jar:?] {}
... 41 more

**Comment by Chumbanotz** [comment]
This is fixed in the latest version: https://www.curseforge.com/minecraft/mc-mods/mutant-beasts/files/2955370.
