### ISSUE TITLE
1.16.1Method public static void？

### ISSUE THREAD

**Issue by Aikini** [Chumbanotz/MutantBeasts#20]
```
[29七月2020 21:24:44.898] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Aikini, --version, HMCL 3.2.139, --gameDir, E:\1.14.4fabric整合V1.2\.minecraft, --assetsDir, E:\1.14.4fabric整合V1.2\.minecraft\assets, --assetIndex, 1.16, --uuid, 67ebefdacff540a0a974a181dc693423, --accessToken, ????????, --userType, mojang, --versionType, HMCL 3.2.139, --width, 1280, --height, 960, --launchTarget, fmlclient, --fml.forgeVersion, 32.0.93, --fml.mcVersion, 1.16.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200625.160719]
[29七月2020 21:24:44.924] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 6.1.1+74+master.966c698 starting: java version 1.8.0_231 by Oracle Corporation
[29七月2020 21:24:46.615] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[29七月2020 21:24:46.728] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/E:/1.14.4fabric%e6%95%b4%e5%90%88V1.2/.minecraft/libraries/org/spongepowered/mixin/0.8/mixin-0.8.jar Service=ModLauncher Env=CLIENT
[29七月2020 21:24:51.892] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, HMCL 3.2.139, --gameDir, E:\1.14.4fabric整合V1.2\.minecraft, --assetsDir, E:\1.14.4fabric整合V1.2\.minecraft\assets, --uuid, 67ebefdacff540a0a974a181dc693423, --username, Aikini, --assetIndex, 1.16, --accessToken, ????????, --userType, mojang, --versionType, HMCL 3.2.139, --width, 1280, --height, 960]
[29七月2020 21:25:34.546] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[29七月2020 21:25:34.729] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: Aikini
[29七月2020 21:25:35.295] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.2.2 build 10
[29七月2020 21:25:39.433] [modloading-worker-2/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 32.0.93, for MC 1.16.1 with MCP 20200625.160719
[29七月2020 21:25:39.435] [modloading-worker-2/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v32.0.93 Initialized
[29七月2020 21:25:39.708] [modloading-worker-1/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: mutantbeasts, class chumbanotz.mutantbeasts.MutantBeasts
java.lang.IllegalArgumentException: Method public static void chumbanotz.mutantbeasts.client.ClientEventHandler.onModelRegistry(net.minecraftforge.client.event.ModelRegistryEvent) has @SubscribeEvent annotation, but takes an argument that is not a subtype of the base type interface net.minecraftforge.fml.event.lifecycle.IModBusEvent: class net.minecraftforge.client.event.ModelRegistryEvent
	at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:145) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$registerClass$2(EventBus.java:78) ~[eventbus-3.0.3-service.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_231]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_231]
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:78) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[?:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_231]
	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:143) ~[?:32.0]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_231]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_231]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:135) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_231]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[?:1.8.0_231]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[?:1.8.0_231]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_231]
	at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source) ~[?:1.8.0_231]
	at java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:1.8.0_231]
	at net.minecraftforge.fml.ModList.lambda$dispatchParallelEvent$11(ModList.java:135) ~[?:?]
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_231]
[29七月2020 21:25:40.687] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[29七月2020 21:25:40.687] [Render thread/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:317) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:111) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:93) ~[?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:425) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:149) ~[1.16.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.1-32.0.93.jar:32.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?]
[29七月2020 21:25:44.644] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[29七月2020 21:25:45.419] [Render thread/INFO] [net.minecraft.resources.SimpleReloadableResourceManager/]: Reloading ResourceManager: Mod Resources, Default, Programmer Art
[29七月2020 21:25:45.576] [Worker-Main-8/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Configuration file E:\1.14.4fabric整合V1.2\.minecraft\config\forge-client.toml is not correct. Correcting
[29七月2020 21:25:45.577] [Worker-Main-8/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key client.useCombinedDepthStencilAttachment was corrected from null to false
[29七月2020 21:25:45.667] [Worker-Main-8/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Configuration file E:\1.14.4fabric整合V1.2\.minecraft\config\mutantbeasts-common.toml is not correct. Correcting
[29七月2020 21:25:45.667] [Worker-Main-8/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key common.mutantCreeperSpawnWeight was corrected from null to 4
[29七月2020 21:25:45.668] [Worker-Main-8/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key common.mutantEndermanSpawnWeight was corrected from null to 3
[29七月2020 21:25:45.668] [Worker-Main-8/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key common.mutantSkeletonSpawnWeight was corrected from null to 4
[29七月2020 21:25:45.668] [Worker-Main-8/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key common.mutantZombieSpawnWeight was corrected from null to 4
[29七月2020 21:25:45.669] [Worker-Main-8/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key common.biomeWhitelist was corrected from null to [minecraft]
[29七月2020 21:25:45.669] [Worker-Main-8/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key common.globalSpawnRate was corrected from 10 to null
[29七月2020 21:25:45.672] [Worker-Main-8/ERROR] [net.minecraftforge.fml.ModLoader/LOADING]: Skipping lifecycle event SETUP, 1 errors found.
[29七月2020 21:25:45.683] [Worker-Main-8/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event SETUP, 1 errors found
[29七月2020 21:25:45.683] [Worker-Main-8/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:317) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:111) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:119) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$3(ClientModLoader.java:101) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:109) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_231]
[29七月2020 21:25:53.923] [Worker-Main-9/ERROR] [net.minecraftforge.fml.ModLoader/LOADING]: Skipping lifecycle event ENQUEUE_IMC, 1 errors found.
[29七月2020 21:25:53.923] [Worker-Main-9/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event ENQUEUE_IMC, 1 errors found
[29七月2020 21:25:53.924] [Worker-Main-9/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:317) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:111) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.finishModLoading(ClientModLoader.java:133) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$4(ClientModLoader.java:103) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniRun(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_231]
[29七月2020 21:25:54.788] [Render thread/INFO] [net.minecraft.client.audio.SoundSystem/]: OpenAL initialized.
[29七月2020 21:25:54.789] [Render thread/INFO] [net.minecraft.client.audio.SoundEngine/SOUNDS]: Sound engine started
[29七月2020 21:25:55.415] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 1024x512x3 minecraft:textures/atlas/blocks.png-atlas
[29七月2020 21:25:55.534] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x128x3 minecraft:textures/atlas/signs.png-atlas
[29七月2020 21:25:55.535] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x3 minecraft:textures/atlas/banner_patterns.png-atlas
[29七月2020 21:25:55.537] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x3 minecraft:textures/atlas/shield_patterns.png-atlas
[29七月2020 21:25:55.538] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x3 minecraft:textures/atlas/chest.png-atlas
[29七月2020 21:25:55.539] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x3 minecraft:textures/atlas/beds.png-atlas
[29七月2020 21:25:55.540] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x3 minecraft:textures/atlas/shulker_boxes.png-atlas
[29七月2020 21:25:56.749] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[29七月2020 21:25:56.753] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[29七月2020 21:25:56.754] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas

```

**Comment by Chumbanotz** [comment]
Should be fixed as of version 1.1.1.
